const PRODUCT_IMAGES = {
  philadelphia: "https://toki.su/__/images/menuProduct/67ecd386481ff_w900_jpg.webp",
  canada: "https://toki.su/__/images/menuProduct/67ecd459bdcad_w900_jpg.webp",
  california: "https://toki.su/__/images/menuProduct/67ecd3032fc6f_w900_jpg.webp",
  philadelphiaEbi: "https://toki.su/__/images/menuProduct/67ecd420a1728_w900_jpg.webp",
  ebiRoll: "https://toki.su/__/images/menuProduct/67ecd58ec2efb_w900_jpg.webp",
  green: "https://toki.su/__/images/menuProduct/67ecd521564a8_w900_jpg.webp",
  philadelphiaSpicy: "https://toki.su/__/images/menuProduct/67ece7c60edb2_w900_jpg.webp",
  opalennayaPhiladelphia: "https://toki.su/__/images/menuProduct/67ecd403c3ee4_w900_jpg.webp",
  bakedPhiladelphia: "https://toki.su/__/images/menuProduct/67ecd1f952d6a_w900_jpg.webp",
  bakedSalmon: "https://toki.su/__/images/menuProduct/67ecd1c143f44_w900_jpg.webp",
  bakedEel: "https://toki.su/__/images/menuProduct/67ecd18a9f7d6_w900_jpg.webp",
  rollTomYam: "https://toki.su/__/images/menuProduct/67ece9e623e49_w900_jpg.webp",
  redVelvet: "https://toki.su/__/images/menuProduct/67ece6e8acca4_w900_jpg.webp",
  ebiTempura: "https://toki.su/__/images/menuProduct/67ecc989569d5_w900_jpg.webp",
  royalTempura: "https://toki.su/__/images/menuProduct/67ecd0eddc605_w900_jpg.webp",
  tempuranSalmon: "https://toki.su/__/images/menuProduct/67ecd12a10b5a_w900_jpg.webp",
  tempuranShrimp: "https://toki.su/__/images/menuProduct/67ecd13fa3670_w900_jpg.webp",
  philadelphiaBig: "https://toki.su/__/images/menuProduct/67ece7daa2555_w900_jpg.webp",
  canadaBig: "https://toki.su/__/images/menuProduct/67ece58c146f4_w900_jpg.webp",
};

const CATEGORY_NAMES = {
  classic: "Классические роллы",
  baked: "Запечённые роллы",
  fried: "Жареные роллы",
  big: "BIG роллы",
};

function createProduct(input) {
  return {
    id: input.id,
    slug: input.slug || input.id,
    name: input.name,
    categoryId: input.categoryId,
    subcategory: input.subcategory,
    description: input.description,
    composition: input.composition,
    weight: input.weight,
    price: input.price,
    image: input.image || "",
    badges: input.badges || [],
    featured: Boolean(input.featured),
    premium: Boolean(input.premium),
    spicy: Boolean(input.spicy),
    available: input.available !== false,
    nutrition: input.nutrition,
    modifiers: input.modifiers || [],
    relatedIds: input.relatedIds || [],
    sortOrder: input.sortOrder || 0,
  };
}

const standardModifiers = {
  extraCheese: { id: "extra-cheese", name: "Творожный сыр x2", price: 120 },
  extraSalmon: { id: "extra-salmon", name: "Доп. лосось", price: 190 },
  extraEel: { id: "extra-eel", name: "Доп. угорь", price: 210 },
  spicySauce: { id: "spicy-sauce", name: 'Соус "Спайси"', price: 50 },
  unagiSauce: { id: "unagi-sauce", name: 'Соус "Унаги"', price: 50 },
  tempuraCrunch: { id: "tempura-crunch", name: "Хрустящий топпинг", price: 70 },
};

export const TOKI23_CATEGORIES = [
  {
    id: "classic-rolls",
    slug: "classic-rolls",
    name: CATEGORY_NAMES.classic,
    subtitle: "Классика Токи23 с лососем, угрём, креветкой и фирменными соусами.",
    active: true,
    sortOrder: 1,
  },
  {
    id: "baked-rolls",
    slug: "baked-rolls",
    name: CATEGORY_NAMES.baked,
    subtitle: "Тёплые роллы с запечёнными шапочками, сырными и острыми акцентами.",
    active: true,
    sortOrder: 2,
  },
  {
    id: "fried-rolls",
    slug: "fried-rolls",
    name: CATEGORY_NAMES.fried,
    subtitle: "Хрустящие темпурные позиции с панко, кляром и насыщенными соусами.",
    active: true,
    sortOrder: 3,
  },
  {
    id: "big-rolls",
    slug: "big-rolls",
    name: CATEGORY_NAMES.big,
    subtitle: "Увеличенные версии хитов для большого аппетита.",
    active: true,
    sortOrder: 4,
  },
];

// Synced from official Toki23 product pages (March 2026).
export const TOKI23_PRODUCTS = [
  createProduct({
    id: "philadelphia",
    name: "Филадельфия",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Классическое сочетание нежного сливочного сыра, свежего огурчика и охлажденного лосося. Идеальный баланс вкусов и текстур для истинных гурманов!",
    composition: "Нори, рис, творожный сыр, лосось, огурцы.",
    weight: 270,
    price: 890,
    image: PRODUCT_IMAGES.philadelphia,
    badges: ["top"],
    featured: true,
    nutrition: { calories: 537.3, protein: 24.3, fat: 21.6, carbs: 27 },
    modifiers: [standardModifiers.extraSalmon, standardModifiers.extraCheese],
    relatedIds: ["canada", "philadelphia-ebi", "green"],
    sortOrder: 1,
  }),
  createProduct({
    id: "canada",
    name: "Канада",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Это классика с изысканным вкусом! Нежный сливочный сыр, свежий огурчик и аппетитный охлажденный лосось гармонично сочетаются внутри. Сверху ролл покрыт нежными ломтиками копченого угря, политыми ароматным соусом унаги и посыпанными кунжутом. Идеальный выбор для ценителей утонченной японской кухни!",
    composition: 'Нори, рис, творожный сыр, лосось, огурцы, угорь, соус "Унаги", кунжут.',
    weight: 260,
    price: 900,
    image: PRODUCT_IMAGES.canada,
    badges: ["premium"],
    featured: true,
    premium: true,
    nutrition: { calories: 569.4, protein: 18.2, fat: 23.4, carbs: 36.4 },
    modifiers: [standardModifiers.extraEel, standardModifiers.unagiSauce],
    relatedIds: ["philadelphia", "opalennaya-philadelphia", "canada-big"],
    sortOrder: 2,
  }),
  createProduct({
    id: "california",
    name: "Калифорния",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Классика японской кухни! Нежный краб-микс и хрустящий огурчик, обернутый в воздушный рис и покрытый яркой икрой масаго. Идеальное сочетание вкусов и текстур для истинных гурманов!",
    composition: "Нори, рис, микс-краб, огурцы, икра масаго.",
    weight: 230,
    price: 520,
    image: PRODUCT_IMAGES.california,
    badges: ["new"],
    nutrition: { calories: 448.5, protein: 13.8, fat: 11.5, carbs: 34.5 },
    modifiers: [standardModifiers.spicySauce],
    relatedIds: ["philadelphia-ebi", "baked-salmon", "ebi-tempura"],
    sortOrder: 3,
  }),
  createProduct({
    id: "philadelphia-ebi",
    name: "Филадельфия Эби",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Изысканный ролл с нежными креветками, сливочным сыром, свежим огурчиком и воздушным рисом. Сочетание свежести морепродуктов и мягкости сыра создаёт гармоничный вкус, который порадует каждого гурмана.",
    composition: "Нори, рис, творожный сыр, лосось, огурцы, креветки.",
    weight: 230,
    price: 620,
    image: PRODUCT_IMAGES.philadelphiaEbi,
    nutrition: { calories: 466.9, protein: 18.4, fat: 16.1, carbs: 25.3 },
    modifiers: [standardModifiers.extraCheese, standardModifiers.spicySauce],
    relatedIds: ["philadelphia", "ebi-roll", "green"],
    sortOrder: 4,
  }),
  createProduct({
    id: "ebi-roll",
    name: "Эби ролл",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Нежный сливочный сыр и свежий хрустящий огурчик внутри, а сверху сочная креветка под пикантным соусом манго-маракуйя. Легкий, освежающий вкус с яркими тропическими нотками. Идеальный выбор для ценителей оригинальных сочетаний!",
    composition: 'Нори, рис, креветки, творожный сыр, огурцы, соус "Манго-Маракуйя".',
    weight: 260,
    price: 660,
    image: PRODUCT_IMAGES.ebiRoll,
    badges: ["top"],
    featured: true,
    nutrition: { calories: 624, protein: 20.8, fat: 28.6, carbs: 28.6 },
    modifiers: [standardModifiers.spicySauce, standardModifiers.tempuraCrunch],
    relatedIds: ["philadelphia-ebi", "california", "ebi-tempura"],
    sortOrder: 5,
  }),
  createProduct({
    id: "green",
    name: "Green",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Лёгкость и свежесть в каждом кусочке! Нежный сливочный сыр и хрустящий огурчик внутри, обёрнуты в изысканный маминори. Сверху ролл украшен аппетитной шапочкой из сочной креветки, пикантного соуса спайси и свежего зелёного лука. Идеальный выбор для любителей гармоничного вкуса с яркими акцентами!",
    composition: 'Маменори, рис, творожный сыр, огурцы, креветки, зелёный лук, соус "Спайси".',
    weight: 240,
    price: 650,
    image: PRODUCT_IMAGES.green,
    badges: ["premium"],
    premium: true,
    nutrition: { calories: 585.6, protein: 19.2, fat: 28.8, carbs: 28.8 },
    modifiers: [standardModifiers.extraSalmon],
    relatedIds: ["philadelphia", "philadelphia-spicy", "opalennaya-philadelphia"],
    sortOrder: 6,
  }),
  createProduct({
    id: "philadelphia-spicy",
    name: "Филадельфия SPICY",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Изысканный ролл для любителей ярких вкусов. Нежный опалённый лосось сочетается с сочными креветками и нежным микс-крабом, а пикантный соус спайси придаёт блюду насыщенность и лёгкую остроту. Идеальный выбор для гурманов!",
    composition: 'Рис, нори, микс-краб, креветка, соус "Спайси", лосось.',
    weight: 240,
    price: 599,
    image: PRODUCT_IMAGES.philadelphiaSpicy,
    badges: ["spicy"],
    spicy: true,
    nutrition: { calories: 605.8, protein: 23.4, fat: 26, carbs: 33.8 },
    modifiers: [standardModifiers.extraSalmon, standardModifiers.spicySauce],
    relatedIds: ["green", "roll-tom-yam", "philadelphia"],
    sortOrder: 7,
  }),
  createProduct({
    id: "opalennaya-philadelphia",
    name: "Опаленная Филадельфия",
    categoryId: "classic-rolls",
    subcategory: CATEGORY_NAMES.classic,
    description:
      "Изысканный ролл с нежным сливочным сыром, свежими огурчиками и опаленным лососем. Завершается блюдо ярким тропическим акцентом - соусом манго-маракуйя, который добавляет утончённую остро-кислую нотку. Идеальное сочетание для ценителей необычных вкусов!",
    composition: 'Нори, рис, творожный сыр, лосось, огурцы, соус "Манго".',
    weight: 290,
    price: 790,
    image: PRODUCT_IMAGES.opalennayaPhiladelphia,
    badges: ["premium"],
    premium: true,
    nutrition: { calories: 580, protein: 22.5, fat: 27.5, carbs: 25 },
    modifiers: [standardModifiers.extraSalmon, standardModifiers.unagiSauce],
    relatedIds: ["canada", "green", "baked-philadelphia"],
    sortOrder: 8,
  }),
  createProduct({
    id: "baked-philadelphia",
    name: "Запечённая филадельфия",
    categoryId: "baked-rolls",
    subcategory: CATEGORY_NAMES.baked,
    description:
      "Нежный ролл с мягким сливочным сыром, хрустящим огурчиком и свежим лососем. Запекание придает блюду насыщенный вкус и аппетитную золотистую корочку. Завершается композиция ароматным унаги соусом, который добавляет легкую сладость и изысканную глубину вкуса. Идеальное сочетание для любителей теплых роллов!",
    composition: 'Нори, рис, творожный сыр, огурцы, лосось, соус "Унаги".',
    weight: 280,
    price: 890,
    image: PRODUCT_IMAGES.bakedPhiladelphia,
    badges: ["top"],
    featured: true,
    nutrition: { calories: 551.6, protein: 25.2, fat: 19.6, carbs: 33.6 },
    modifiers: [standardModifiers.extraCheese, standardModifiers.unagiSauce],
    relatedIds: ["baked-salmon", "baked-eel", "philadelphia"],
    sortOrder: 9,
  }),
  createProduct({
    id: "baked-salmon",
    name: "Запечённый с лососем",
    categoryId: "baked-rolls",
    subcategory: CATEGORY_NAMES.baked,
    description:
      'Запечённый ролл обваленный в икринках масаго красного или оранжевого цвета с нежной начинкой из творожного сыра и охлажденного лосося, под шапочкой из "Чесночно-сырного" соуса. ВАЖНО: Не приезжает горячим. *Внешний вид продукта может отличаться от фото',
    composition:
      'Нори, рис, творожный сыр, лосось, соус "Чесночно-сырный", икра масаго красная или оранжевая.',
    weight: 280,
    price: 600,
    image: PRODUCT_IMAGES.bakedSalmon,
    nutrition: { calories: 803.6, protein: 22.4, fat: 47.6, carbs: 33.6 },
    modifiers: [standardModifiers.extraCheese, standardModifiers.spicySauce],
    relatedIds: ["baked-philadelphia", "roll-tom-yam", "california"],
    sortOrder: 10,
  }),
  createProduct({
    id: "baked-eel",
    name: "Запечённый с угрем",
    categoryId: "baked-rolls",
    subcategory: CATEGORY_NAMES.baked,
    description:
      "Гармоничное сочетание нежного угря, сливочного сыра и свежего огурчика, завернутых в рис и нори. Снаружи ролл обвален в ароматной стружке тунца, которая придает блюду изысканный вкус. Сверху - аппетитная шапочка из чесночно-сырного соуса, покрытая ароматным соусом унаги. Идеальный выбор для ценителей насыщенных и сбалансированных вкусов!",
    composition:
      'Нори, рис, угорь, творожный сыр, огурцы, стружка тунца, соус "Чесночно-сырный", соус "Унаги".',
    weight: 270,
    price: 580,
    image: PRODUCT_IMAGES.bakedEel,
    badges: ["premium"],
    premium: true,
    nutrition: { calories: 796.5, protein: 21.6, fat: 45.9, carbs: 37.8 },
    modifiers: [standardModifiers.extraEel, standardModifiers.unagiSauce],
    relatedIds: ["baked-philadelphia", "canada", "roll-tom-yam"],
    sortOrder: 11,
  }),
  createProduct({
    id: "roll-tom-yam",
    name: "Ролл Том-Ям",
    categoryId: "baked-rolls",
    subcategory: CATEGORY_NAMES.baked,
    description:
      "Изысканное сочетание морепродуктов и ярких вкусов. Нежные мидии, сочные креветки, сливочный сыр, свежий зеленый лук и спелые томаты создают гармоничную начинку. Ролл обвален в икре масаго, добавляющей легкую хрустящую текстуру. Завершает блюдо аппетитная запеченная шапочка из пикантного соуса Том-Ям, которая придает роллу насыщенный азиатский акцент. Настоящий гастрономический шедевр для любителей ярких и необычных вкусов!",
    composition:
      'Рис, нори, мидии, сыр творожный, креветки, зелёный лук, томаты, икра масаго, соус "Том-Ям".',
    weight: 300,
    price: 590,
    image: PRODUCT_IMAGES.rollTomYam,
    badges: ["spicy"],
    spicy: true,
    nutrition: { calories: 625, protein: 20, fat: 32.5, carbs: 30 },
    modifiers: [standardModifiers.spicySauce, standardModifiers.tempuraCrunch],
    relatedIds: ["baked-salmon", "philadelphia-spicy", "ebi-tempura"],
    sortOrder: 12,
  }),
  createProduct({
    id: "red-velvet",
    name: "Красный бархат",
    categoryId: "baked-rolls",
    subcategory: CATEGORY_NAMES.baked,
    description:
      "Изысканное сочетание нежного лосося, сочного тунца и сливочного сыра. Ролл обвален в яркой икре масаго, которая придает блюду насыщенный вкус и текстуру. Завершает композицию фирменная запеченная шапочка, добавляющая нежности и делая этот ролл настоящим гастрономическим шедевром.",
    composition:
      'Рис, нори, лосось, тунец, сыр творожный, соус "Фирменный", икра масаго красная, оранжевая, зелёная или чёрная.',
    weight: 260,
    price: 660,
    image: PRODUCT_IMAGES.redVelvet,
    badges: ["new"],
    nutrition: { calories: 748.8, protein: 26, fat: 44.2, carbs: 28.6 },
    modifiers: [standardModifiers.extraCheese],
    relatedIds: ["baked-philadelphia", "roll-tom-yam", "opalennaya-philadelphia"],
    sortOrder: 13,
  }),
  createProduct({
    id: "ebi-tempura",
    name: "Эби темпура",
    categoryId: "fried-rolls",
    subcategory: CATEGORY_NAMES.fried,
    description:
      'Жареный ролл с сочной креветкой и нежным сливочным сыром, обжаренный в хрустящей темпуре и покрытый пикантным соусом спайси. Идеальное сочетание яркого вкуса и аппетитной текстуры!',
    composition: 'Нори, рис, творожный сыр, креветки, сухарики панко, кляр, соус "Спайси".',
    weight: 280,
    price: 500,
    image: PRODUCT_IMAGES.ebiTempura,
    badges: ["top"],
    featured: true,
    nutrition: { calories: 761.6, protein: 16.8, fat: 30.8, carbs: 67.2 },
    modifiers: [standardModifiers.tempuraCrunch, standardModifiers.spicySauce],
    relatedIds: ["royal-tempura", "tempuran-salmon", "ebi-roll"],
    sortOrder: 14,
  }),
  createProduct({
    id: "royal-tempura",
    name: "Королевская темпура",
    categoryId: "fried-rolls",
    subcategory: CATEGORY_NAMES.fried,
    description:
      'Жареный ролл с нежным лососем, сочным микс-крабом и свежим огурчиком. Обжарен до хрустящей корочки и дополнен ароматным соусом унаги для насыщенного вкуса.',
    composition: 'Нори, рис, микс-краб, лосось, огурцы, сухарики панко, кляр, соус "Унаги".',
    weight: 290,
    price: 540,
    image: PRODUCT_IMAGES.royalTempura,
    badges: ["premium"],
    featured: true,
    premium: true,
    nutrition: { calories: 638, protein: 20.3, fat: 14.5, carbs: 72.5 },
    modifiers: [standardModifiers.unagiSauce, standardModifiers.tempuraCrunch],
    relatedIds: ["ebi-tempura", "tempuran-salmon", "canada"],
    sortOrder: 15,
  }),
  createProduct({
    id: "tempuran-salmon",
    name: "ТемпуРАН с лососем",
    categoryId: "fried-rolls",
    subcategory: CATEGORY_NAMES.fried,
    description:
      'Жареный ролл с нежным сливочным сыром и свежим огурчиком внутри, покрытый аппетитной шапочкой из сочного лосося, ароматного зеленого лука и пикантного соуса спайси. Завершается блюдо изысканной глазурью соуса унаги - гармония вкусов в каждой порции!',
    composition:
      'Нори, рис, творожный сыр, огурцы, лосось, зелёный лук, сухарики панко, кляр, соус "Спайси", соус "Унаги".',
    weight: 330,
    price: 650,
    image: PRODUCT_IMAGES.tempuranSalmon,
    badges: ["top"],
    featured: true,
    nutrition: { calories: 861.3, protein: 23.1, fat: 36.3, carbs: 75.9 },
    modifiers: [standardModifiers.extraSalmon, standardModifiers.tempuraCrunch],
    relatedIds: ["royal-tempura", "tempuran-shrimp", "philadelphia-big"],
    sortOrder: 16,
  }),
  createProduct({
    id: "tempuran-shrimp",
    name: "ТемпуРАН с креветкой",
    categoryId: "fried-rolls",
    subcategory: CATEGORY_NAMES.fried,
    description:
      'Жареный ролл с нежным сливочным сыром и хрустящим огурчиком внутри, увенчанный аппетитной шапочкой из сочного замеса креветки, ароматного зеленого лука и пикантного соуса спайси. Завершается блюдо изысканной глазурью соуса унаги - насыщенный вкус в каждой детали!',
    composition:
      'Нори, рис, творожный сыр, огурцы, креветки, зелёный лук, сухарики панко, кляр, соус "Спайси", соус "Унаги".',
    weight: 330,
    price: 600,
    image: PRODUCT_IMAGES.tempuranShrimp,
    nutrition: { calories: 844.8, protein: 23.1, fat: 33, carbs: 75.9 },
    modifiers: [standardModifiers.spicySauce, standardModifiers.tempuraCrunch],
    relatedIds: ["tempuran-salmon", "ebi-tempura", "philadelphia-ebi"],
    sortOrder: 17,
  }),
  createProduct({
    id: "philadelphia-big",
    name: "Филадельфия БИГ",
    categoryId: "big-rolls",
    subcategory: CATEGORY_NAMES.big,
    description:
      'Увеличенная версия всеми любимой классики! Щедрый слой нежного охлажденного лосося, сливочный сыр и свежий огурчик в сочетании с идеально приготовленным рисом создают насыщенный вкус и дарят максимум удовольствия. Для тех, кто хочет больше вкуса и удовольствия в каждом кусочке!',
    composition: "Рис, нори, сыр творожный, огурцы, лосось.",
    weight: 350,
    price: 1000,
    image: PRODUCT_IMAGES.philadelphiaBig,
    badges: ["premium"],
    featured: true,
    premium: true,
    nutrition: { calories: 724.5, protein: 28, fat: 31.5, carbs: 35 },
    modifiers: [standardModifiers.extraSalmon, standardModifiers.extraCheese],
    relatedIds: ["canada-big", "philadelphia", "tempuran-salmon"],
    sortOrder: 18,
  }),
  createProduct({
    id: "canada-big",
    name: "Канада БИГ",
    categoryId: "big-rolls",
    subcategory: CATEGORY_NAMES.big,
    description:
      'Увеличенная версия любимой классики! Внутри - нежный сливочный сыр, свежий огурчик и сочный лосось. Снаружи - аппетитный копченый угорь, покрытый ароматным соусом унаги и посыпанный кунжутом. Максимум вкуса и удовольствия в каждом большом кусочке!',
    composition: 'Рис, нори, сыр творожный, огурцы, лосось, угорь, соус "Унаги", кунжут.',
    weight: 350,
    price: 1100,
    image: PRODUCT_IMAGES.canadaBig,
    badges: ["premium"],
    premium: true,
    nutrition: { calories: 773.5, protein: 31.5, fat: 31.5, carbs: 45.5 },
    modifiers: [standardModifiers.extraEel, standardModifiers.unagiSauce],
    relatedIds: ["philadelphia-big", "canada", "opalennaya-philadelphia"],
    sortOrder: 19,
  }),
];
